// <auto-generated />
using System;
using ECAR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECAR.Infrastructure.Migrations
{
    [DbContext(typeof(ECARDbContext))]
    [Migration("20261010022407_Fase4HallazgosAuditoria")]
    partial class Fase4HallazgosAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Auditoria", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdAuditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Accion");

                    b.Property<string>("AgenteUsuario")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("AgenteUsuario");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DireccionIp");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("Hash");

                    b.Property<string>("HashAnterior")
                        .HasColumnType("char(64)")
                        .HasColumnName("HashAnterior");

                    b.Property<long?>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Motivo");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("RegistroId");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tabla");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorAnterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorNuevo");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("Accion");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("RegistroId");

                    b.HasIndex("Tabla");

                    b.HasIndex("Usuario");

                    b.HasIndex("Tabla", "RegistroId", "FechaHora");

                    b.ToTable("Auditoria", t =>
                        {
                            t.HasTrigger("TR_Auditoria_SoloInsercion");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.CategoriaEquipo", b =>
                {
                    b.Property<long>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasEquipo");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Checklist", b =>
                {
                    b.Property<long>("IdChecklist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdChecklist");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdChecklist"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Version");

                    b.HasKey("IdChecklist");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre", "Version")
                        .IsUnique();

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Equipo", b =>
                {
                    b.Property<long>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdEquipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEquipo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("ActivoFijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ActivoFijo");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoInterno");

                    b.Property<string>("Criticidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Criticidad");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Fabricante");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("FrecuenciaInspeccion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FrecuenciaInspeccion");

                    b.Property<long?>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("IdCategoria");

                    b.Property<long?>("IdUbicacion")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUbicacion");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Modelo");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreEquipo");

                    b.Property<string>("QRCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("QRCode");

                    b.Property<string>("SerialFabricante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SerialFabricante");

                    b.HasKey("IdEquipo");

                    b.HasIndex("ActivoFijo")
                        .IsUnique();

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("Criticidad");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUbicacion");

                    b.HasIndex("QRCode")
                        .IsUnique()
                        .HasFilter("[QRCode] IS NOT NULL");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Evidencia", b =>
                {
                    b.Property<long>("IdEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdEvidencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEvidencia"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Archivo");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCarga");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRetiro");

                    b.Property<long>("IdInspeccion")
                        .HasColumnType("bigint")
                        .HasColumnName("IdInspeccion");

                    b.Property<long>("IdUsuarioCarga")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuarioCarga");

                    b.Property<long?>("IdUsuarioRetiro")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuarioRetiro");

                    b.Property<string>("MotivoRetiro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotivoRetiro");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreOriginal");

                    b.Property<bool>("Retirada")
                        .HasColumnType("bit")
                        .HasColumnName("Retirada");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("TamanoBytes");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TipoContenido");

                    b.HasKey("IdEvidencia");

                    b.HasIndex("FechaCarga");

                    b.HasIndex("IdInspeccion");

                    b.HasIndex("IdUsuarioCarga");

                    b.HasIndex("IdUsuarioRetiro");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Hallazgo", b =>
                {
                    b.Property<long>("IdHallazgo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdHallazgo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdHallazgo"));

                    b.Property<string>("AccionCorrectiva")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AccionCorrectiva");

                    b.Property<string>("Criticidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Criticidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Abierto")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCierre");

                    b.Property<DateTime?>("FechaCompromiso")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCompromiso");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<long>("IdInspeccion")
                        .HasColumnType("bigint")
                        .HasColumnName("IdInspeccion");

                    b.Property<long?>("IdPregunta")
                        .HasColumnType("bigint")
                        .HasColumnName("IdPregunta");

                    b.Property<long?>("IdUsuarioCierre")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuarioCierre");

                    b.Property<long>("IdUsuarioRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuarioRegistro");

                    b.Property<long?>("IdUsuarioResponsable")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuarioResponsable");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotivoAnulacion");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("Origen");

                    b.HasKey("IdHallazgo");

                    b.HasIndex("Criticidad");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdInspeccion");

                    b.HasIndex("IdPregunta");

                    b.HasIndex("IdUsuarioCierre");

                    b.HasIndex("IdUsuarioRegistro");

                    b.HasIndex("IdUsuarioResponsable");

                    b.ToTable("Hallazgos");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.HistorialPassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "Fecha");

                    b.ToTable("HistorialPasswords");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Inspeccion", b =>
                {
                    b.Property<long>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdInspeccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdInspeccion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("EnCurso")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAnulacion");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCierre");

                    b.Property<DateTime>("FechaInspeccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaInspeccion");

                    b.Property<string>("FirmaAlgoritmo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("FirmaAlgoritmo");

                    b.Property<string>("FirmaDigital")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirmaDigital");

                    b.Property<string>("FirmaHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("FirmaHash");

                    b.Property<string>("FirmaNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FirmaNombre");

                    b.Property<string>("FirmaSignificado")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FirmaSignificado");

                    b.Property<long>("IdChecklist")
                        .HasColumnType("bigint")
                        .HasColumnName("IdChecklist");

                    b.Property<long>("IdEquipo")
                        .HasColumnType("bigint")
                        .HasColumnName("IdEquipo");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuario");

                    b.Property<long?>("IdUsuarioAnulacion")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuarioAnulacion");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotivoAnulacion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<string>("Resultado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Resultado");

                    b.HasKey("IdInspeccion");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaInspeccion");

                    b.HasIndex("IdChecklist");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioAnulacion");

                    b.HasIndex("Resultado");

                    b.HasIndex("IdUsuario", "Estado");

                    b.ToTable("Inspecciones");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.PreguntaChecklist", b =>
                {
                    b.Property<long>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdPregunta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPregunta"));

                    b.Property<long>("IdChecklist")
                        .HasColumnType("bigint")
                        .HasColumnName("IdChecklist");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("bit")
                        .HasColumnName("Obligatoria");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pregunta");

                    b.Property<string>("TipoRespuesta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoRespuesta");

                    b.HasKey("IdPregunta");

                    b.HasIndex("IdChecklist");

                    b.HasIndex("TipoRespuesta");

                    b.ToTable("PreguntasChecklist");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.RespuestaInspeccion", b =>
                {
                    b.Property<long>("IdRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdRespuesta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRespuesta"));

                    b.Property<long>("IdInspeccion")
                        .HasColumnType("bigint")
                        .HasColumnName("IdInspeccion");

                    b.Property<long>("IdPregunta")
                        .HasColumnType("bigint")
                        .HasColumnName("IdPregunta");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacion");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Respuesta");

                    b.HasKey("IdRespuesta");

                    b.HasIndex("IdInspeccion");

                    b.HasIndex("IdPregunta");

                    b.HasIndex("IdInspeccion", "IdPregunta")
                        .IsUnique();

                    b.ToTable("RespuestasInspeccion");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Rol", b =>
                {
                    b.Property<long>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Ubicacion", b =>
                {
                    b.Property<long>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdUbicacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUbicacion"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Area");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Planta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Planta");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("Planta", "Area")
                        .IsUnique();

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("BloqueadoHasta");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Correo");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("bit")
                        .HasColumnName("DebeCambiarPassword");

                    b.Property<DateTime?>("FechaCambioPassword")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCambioPassword");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("IntentosFallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("SecurityStamp");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcceso");

                    b.Property<string>("UsuarioAD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UsuarioAD");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("UsuarioAD")
                        .IsUnique()
                        .HasFilter("[UsuarioAD] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint")
                        .HasColumnName("IdRol");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique();

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Auditoria", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Equipo", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.CategoriaEquipo", "Categoria")
                        .WithMany("Equipos")
                        .HasForeignKey("IdCategoria");

                    b.HasOne("ECAR.Infrastructure.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Equipos")
                        .HasForeignKey("IdUbicacion");

                    b.Navigation("Categoria");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Evidencia", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Inspeccion", "Inspeccion")
                        .WithMany("Evidencias")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "UsuarioCargaDetalle")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCarga")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "UsuarioRetiro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRetiro")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Inspeccion");

                    b.Navigation("UsuarioCargaDetalle");

                    b.Navigation("UsuarioRetiro");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Hallazgo", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Inspeccion", "Inspeccion")
                        .WithMany("Hallazgos")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.PreguntaChecklist", "Pregunta")
                        .WithMany()
                        .HasForeignKey("IdPregunta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCierre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Inspeccion");

                    b.Navigation("Pregunta");

                    b.Navigation("UsuarioCierre");

                    b.Navigation("UsuarioRegistro");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.HistorialPassword", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "Usuario")
                        .WithMany("HistorialPasswords")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Inspeccion", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Checklist", "Checklist")
                        .WithMany("Inspecciones")
                        .HasForeignKey("IdChecklist")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Equipo", "Equipo")
                        .WithMany("Inspecciones")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "Usuario")
                        .WithMany("Inspecciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "UsuarioAnulacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAnulacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Checklist");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.PreguntaChecklist", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Checklist", "Checklist")
                        .WithMany("Preguntas")
                        .HasForeignKey("IdChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.RespuestaInspeccion", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Inspeccion", "Inspeccion")
                        .WithMany("Respuestas")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.PreguntaChecklist", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("IdPregunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.UsuarioRol", b =>
                {
                    b.HasOne("ECAR.Infrastructure.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECAR.Infrastructure.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.CategoriaEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Checklist", b =>
                {
                    b.Navigation("Inspecciones");

                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Equipo", b =>
                {
                    b.Navigation("Inspecciones");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Inspeccion", b =>
                {
                    b.Navigation("Evidencias");

                    b.Navigation("Hallazgos");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.PreguntaChecklist", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Ubicacion", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ECAR.Infrastructure.Entities.Usuario", b =>
                {
                    b.Navigation("HistorialPasswords");

                    b.Navigation("Inspecciones");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
